#!/bin/bash
. test/integration/helper

setup () {
mkdir -p "$ts_test_dir"
infile="$ts_test_dir/input"
}

test_chart_converts_nxyz_data_into_nxyz_data () {
cat > "$infile" <<DOC
a 1 2 3
b 4 5 6
DOC

chart "$infile" | assert_output "\
a 1 2 3
b 4 5 6
"
}

#
# -h
#

test_chart_h_prints_help () {
chart -h | grep -q "usage: chart"
}

#
# -n
#

test_chart_n_sets_default_n () {
cat > "$infile" <<DOC
1 2 3
4 5 6
DOC

chart -n 0 -i xyz "$infile" | assert_output "\
0 1 2 3
0 4 5 6
"
}

#
# -N
#

test_chart_N_sets_null_string () {
cat > "$infile" <<DOC
a - -
b - -
DOC

chart -x1 -y2 -N - -i nxy "$infile" | assert_output "\
a 1 2 -
b 1 2 -
"
}

#
# -i
#

test_chart_i_assigns_input_order_of_nxyz_data () {
cat > "$infile" <<DOC
3 2 1 a
6 5 4 b
DOC

chart -i zyxn "$infile" | assert_output "\
a 1 2 3
b 4 5 6
"
}

#
# -t
#

test_chart_t_sets_field_defaults_to_now () {
cat > "$infile" <<DOC
2
5
DOC

chart -n a -t xz -i y "$infile" | underscore_times | assert_output "\
a _ 2 _
a _ 5 _
"
}

#
# -x
#

test_chart_x_sets_default_x () {
cat > "$infile" <<DOC
a 2 3
b 5 6
DOC

chart -x 0 -i nyz "$infile" | assert_output "\
a 0 2 3
b 0 5 6
"
}

#
# -y
#

test_chart_y_sets_default_y () {
cat > "$infile" <<DOC
a 1 3
b 4 6
DOC

chart -y 0 -i nxz "$infile" | assert_output "\
a 1 0 3
b 4 0 6
"
}

#
# -z
#

test_chart_z_sets_default_z () {
cat > "$infile" <<DOC
a 1 2
b 4 5
DOC

chart -z 0 -i nxy "$infile" | assert_output "\
a 1 2 0
b 4 5 0
"
}

. ts
